// ============================================
// æŸ¥è¯¢åç§°: Calendar (æ—¥å†è¡?
// æ•°æ®æº? dim_calendar
// è¯´æ˜: å¤åˆ¶æ­¤ä»£ç åˆ° Power BI é«˜çº§ç¼–è¾‘å™?
// ============================================

let
    // æ•°æ®åº“è·¯å¾?- è¯·æ ¹æ®å®é™…è·¯å¾„ä¿®æ”?
    DbPath = "C:\Users\huangk14\OneDrive - Medtronic PLC\Huangkai Files\C_code\CZ_Digital_Central\data_pipelines\database\mddap_v2.db",
    
    // è¿æ¥ SQLite æ•°æ®åº?
    Source = Odbc.Query(
        "Driver={SQLite3 ODBC Driver};Database=" & DbPath,
        "SELECT 
            date,
            weekday,
            weekday_cn,
            calendar_week,
            fiscal_week,
            fiscal_week_label,
            fiscal_month,
            fiscal_quarter,
            fiscal_year,
            fiscal_month_short,
            is_workday,
            holiday_name
        FROM dim_calendar"
    ),
    
    // è½¬æ¢æ•°æ®ç±»å‹
    ChangedType = Table.TransformColumnTypes(Source, {
        {"date", type date},
        {"calendar_week", Int64.Type},
        {"fiscal_week", Int64.Type},
        {"is_workday", Int64.Type}
    })
in
    ChangedType
