// ============================================
// æŸ¥è¯¢åç§°: Labor Hours (å·¥æ—¶æ•°æ®)
// æ•°æ®æº? raw_sap_labor_hours
// è¯´æ˜: å¤åˆ¶æ­¤ä»£ç åˆ° Power BI é«˜çº§ç¼–è¾‘å™?
// ============================================

let
    // æ•°æ®åº“è·¯å¾?- è¯·æ ¹æ®å®é™…è·¯å¾„ä¿®æ”?
    DbPath = "C:\Users\huangk14\OneDrive - Medtronic PLC\Huangkai Files\C_code\CZ_Digital_Central\data_pipelines\database\mddap_v2.db",
    
    // è¿æ¥ SQLite æ•°æ®åº?
    Source = Odbc.Query(
        "Driver={SQLite3 ODBC Driver};Database=" & DbPath,
        "SELECT 
            Plant,
            WorkCenter,
            WorkCenterDesc,
            CostCenter,
            CostCenterDesc,
            Material,
            MaterialDesc,
            MaterialType,
            MRPController,
            MRPControllerDesc,
            ProductionScheduler,
            ProductionSchedulerDesc,
            OrderNumber,
            OrderType,
            OrderTypeDesc,
            Operation,
            OperationDesc,
            PostingDate,
            EarnedLaborUnit,
            MachineTime,
            EarnedLaborTime,
            ActualQuantity,
            ActualScrapQty,
            TargetQuantity
        FROM raw_sap_labor_hours"
    ),
    
    // è½¬æ¢æ•°æ®ç±»å‹
    ChangedType = Table.TransformColumnTypes(Source, {
        {"PostingDate", type date},
        {"MachineTime", type number},
        {"EarnedLaborTime", type number},
        {"ActualQuantity", type number},
        {"ActualScrapQty", type number},
        {"TargetQuantity", type number}
    })
in
    ChangedType
