// ============================================
// æŸ¥è¯¢åç§°: Operation Mapping (å·¥åºæ˜ å°„è¡?
// æ•°æ®æº? dim_operation_mapping
// è¯´æ˜: å¤åˆ¶æ­¤ä»£ç åˆ° Power BI é«˜çº§ç¼–è¾‘å™?
// ============================================

let
    // æ•°æ®åº“è·¯å¾?- è¯·æ ¹æ®å®é™…è·¯å¾„ä¿®æ”?
    DbPath = "C:\Users\huangk14\OneDrive - Medtronic PLC\Huangkai Files\C_code\CZ_Digital_Central\data_pipelines\database\mddap_v2.db",
    
    // è¿æ¥ SQLite æ•°æ®åº?
    Source = Odbc.Query(
        "Driver={SQLite3 ODBC Driver};Database=" & DbPath,
        "SELECT 
            operation_name,
            standard_routing,
            area,
            lead_time,
            erp_code
        FROM dim_operation_mapping"
    ),
    
    // è½¬æ¢æ•°æ®ç±»å‹
    ChangedType = Table.TransformColumnTypes(Source, {
        {"lead_time", type number}
    })
in
    ChangedType
