// ============================================
// æŸ¥è¯¢åç§°: Planned Hours (è®¡åˆ’å·¥æ—¶æ•°æ®)
// æ•°æ®æº? planned_labor_hours
// è¯´æ˜: å¤åˆ¶æ­¤ä»£ç åˆ° Power BI é«˜çº§ç¼–è¾‘å™?
// ============================================

let
    // æ•°æ®åº“è·¯å¾?- è¯·æ ¹æ®å®é™…è·¯å¾„ä¿®æ”?
    DbPath = "C:\Users\huangk14\OneDrive - Medtronic PLC\Huangkai Files\C_code\CZ_Digital_Central\data_pipelines\database\mddap_v2.db",
    
    // è¿æ¥ SQLite æ•°æ®åº?
    Source = Odbc.Query(
        "Driver={SQLite3 ODBC Driver};Database=" & DbPath,
        "SELECT 
            plan_date,
            cz_planned_hours,
            kh_planned_hours,
            is_cz_workday,
            is_kh_workday,
            source_file,
            created_at,
            updated_at
        FROM planned_labor_hours"
    ),
    
    // è½¬æ¢æ•°æ®ç±»å‹
    ChangedType = Table.TransformColumnTypes(Source, {
        {"plan_date", type date},
        {"cz_planned_hours", type number},
        {"kh_planned_hours", type number},
        {"is_cz_workday", type number},
        {"is_kh_workday", type number},
        {"source_file", type text},
        {"created_at", type datetime},
        {"updated_at", type datetime}
    })
in
    ChangedType
